name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to Surge
        run: surge ./ eloso-landing.surge.sh --token ${{ secrets.SURGE_TOKEN }}
